# 站点名称
site_name: Sammary114`s Blog
site_author: Sammary114
site_description: Sammary114 的个人博客
site_url: https://blog.zonelemon.top/

repo_url: https://github.com/sammary114/blog
repo_name: sammary114/blog

# 主题配置
theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - content.code.copy

# 扩展项目
extra:
  social:
    # Github
    - icon: fontawesome/brands/github 
      link: https://github.com/sammary114
      name: Sammary114 on Github
    # Steam
    - icon: fontawesome/brands/steam 
      link: https://steamcommunity.com/id/ZoneLemon
      name: Sammary114 on Steam
    # Telegram
    - icon: fontawesome/brands/telegram
      link: https://t.me/Candyman_13
      name: Sammary114 on Telegram

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - blogging:
      locale: zh_CN
      dirs:
        - blog
      features:
        tags: {}
      theme:
        name: card
        time_format: '%Y-%m-%d %H:%M:%S'
        meta_time_format: '%Y-%m-%d %H:%M:%S'  
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
  - glightbox:
      draggable: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
